#!/usr/bin/env python3
"""Random Instruction Generator for NQ-ASM."""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), "../.."))
from tools.rig import main
sys.exit(main())
